---
baseurl: "//traeblain.com/"
title: "Trae Blain"
metaDataFormat: "yaml"
paginate: 5
languageCode: "en-us"
copyright: "This work is licensed under an All Rights Reserved licensed."
ignoreFiles: ["\\.less$"]
theme: "tbcom"
publishdir: "/www/main/public"
metaDataFormat: "yaml"

author:
  name: Trae Blain


blackfriday:
  plainIDAnchors: true
  extensions:
    - hardLineBreak

params:
  disqus: traeblain
  segment: gveNZnsGRVvfcJKu8CfxI3TgX5buZ0DT
  swiftype: xxvxuPQWopgGHCpFwzi-
  rss: /blog/index.xml

menu:
  main:
    - Name: "Notebook"
      URL: "/blog"
      Weight: 1
      Pre: "<i class='fa fa-home'></i>"
      Identifier: "Notebook"
    - Name: "Facebook"
      URL: "http://facebook.com/traeblain"
      Weight: 2
      Pre: "<i class='fa fa-facebook'></i>"
      Identifier: "Facebook"
    - Name: "Twitter"
      URL: "http://twitter.com/traeblain"
      Weight: 3
      Pre: "<i class='fa fa-twitter'></i>"
      Identifier: "Twitter"
    - Name: "B<span class='small'>the</span>B"
      URL: "http://breakingthebike.com/"
      Weight: 4
      Pre: "<i class='fa fa-bicycle'></i>"
      Identifier: "Breaking the Bike"
    - Name: "Github"
      URL: "http://github.com/traeblain"
      Weight: 5
      Pre: "<i class='fa fa-github'></i>"
      Identifier: "Github"
    - Name: "PGP Info"
      URL: "http://keybase.io/traeblain"
      Weight: 6
      Pre: "<i class='fa fa-lock'></i>"
      Identifier: "PGP Info (Keybase)"
