baseurl = "//traeblain.com/"
copyright = "This work is licensed under an All Rights Reserved licensed."
ignoreFiles = ["\\.less$"]
languageCode = "en-us"
metaDataFormat = "yaml"
publishdir = "public"
theme = "theme2019"
title = "Trae Blain"

[author]
  name = "Trae Blain"
  commonname = "traeblain"

[blackfriday]
  extensions = ["hardLineBreak"]
  plainIDAnchors = true

[menu]

  [[menu.main]]
    identifier = "blog"
    name = "Notebook"
    title = "Notebook"
    url = "/blog"
    weight = 1

  [[menu.main]]
    identifier = "activity"
    name = "Activity"
    title = "Activity"
    url = "/#activity"
    weight = 2

  [[menu.main]]
    identifier = "social"
    name = "Social"
    title = "Social"
    url = "/#social"
    weight = 3
  
  [[menu.main]]
    identifier = "sensory"
    name = "Sensory"
    title = "Sensory"
    url = "/#sensory"
    weight = 4
  
  # [[menu.main]]
  #   identifier = "miscellaneous"
  #   name = "Miscellaneous"
  #   title = "Miscellaneous"
  #   url = "/#miscellaneous"
  #   weight = 5

  [[menu.social]]
    identifier = "twitter"
    name = "Twitter"
    post = "me"
    url = "http://twitter.com/traeblain"
    weight = 2

  [[menu.social]]
    identifier = "instagram"
    name = "Instagram"
    post = "me"
    url = "http://instagram.com/traeblain"
    weight = 3

  [[menu.social]]
    identifier = "linkedin"
    name = "LinkedIn"
    post = "me"
    url = "http://linkedin.com/in/traeblain/"
    weight = 4

  [[menu.social]]
    identifier = "github"
    name = "Github"
    post = "me"
    url = "http://github.com/traeblain"
    weight = 5

  [[menu.social]]
    identifier = "lock"
    name = "PGP Info"
    post = "me"
    url = "http://keybase.io/traeblain"
    weight = 6

  [[menu.social]]
    identifier = "rss"
    name = "RSS"
    url = "/blog/index.xml"
    weight = 7

[params]
  # disqus = "traeblain"
  rss = "/blog/index.xml"
  # segment = "gveNZnsGRVvfcJKu8CfxI3TgX5buZ0DT"
  # swiftype = "xxvxuPQWopgGHCpFwzi-"
  matomo = true
