---
upload_path: "/static/uploads/"
frontmatter_file_url_template: "/uploads/"
body_file_url_template: "/uploads/"
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
  blog:
    default_front_matter_template: blog
version: 0.31.1
