name: cloudinary-cache-clear
run-name: ${{ github.actor }} is clearing Cloudinary cache to pull changes
on: [push, workflow_dispatch]
jobs:
  clear-cache:
    name: Setup Node and Cloudinary then clear cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3.5.1
        with:
          node-version: '19.x'
      - name: Install Cloudinary from npm
        run: npm install -g cloudinary
      - name: List the folders...maybe
        run: ls -ahl ${GITHUB_WORKSPACE}
      - name: Clear the cache
        run: node ${GITHUB_WORKSPACE}/.github/scripts/gh-runner.js
        shell: bash
              
