name: cloudinary-cache-clear
run-name: ${{ github.actor }} is clearing Cloudinary cache to pull changes
on: [push, workflow_dispatch]
jobs:
  clear-cache:
    name: Setup Node and Cloudinary then clear cache
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
      - uses: actions/setup-node@v3.5.1
        with:
          node-version: '14.x'
      - name: Install Cloudinary from npm
      - run: npm install -g cloudinary
      - name: Look at directory
      - run: ls -ahl
      - name: Clear the cache
      - run: ./scripts/gh-runner.js
      
